### ISSUE TITLE
Merging conditions, switch conditions and loop inside one chapter.

### ISSUE THREAD

**Issue by Webd01** [learndev-info/php-tutorial#11]
I personally think that it would be better to merge ``conditions``, ``switch conditions`` and ``loops`` into a single chapter called ``Control flow``. Then, divide this one into sub-chapters. Here is my vision:

- **Control flow**
	* if/else 
	* Switch
	* Loops
		* For
		* While
		* Foreach 

What do you think about that?

**Comment by binksxela** [comment]
Yeah, why not. What do you think about this @rault-a
